language: python
python:
- '2.7'
cache:
  directories:
  - "$HOME/.cache/pip"
env:
  global:
  - PIP_INDEX_URL=https://www.fool.com/a/apikey/$DEVPI_API_KEY/fool/packages/+simple/
  - PACKAGE_NAME=wagtail-automatic-redirects
install:
- pip install -U setuptools
- pip install -U pip
- pip install .
- pip install -U .[test]
script:
- python setup.py test
deploy:
  provider: pypi
  server: https://www.fool.com/a/apikey/$DEVPI_API_KEY/fool/packages/
  skip_upload_docs: true
  user: travisci
  on:
    tags: true
  password:
    secure: HQ8dAhaq4Eo0JFA0AkwSM/tVtkg7SJ4YOChYtuEkSejt3kQAfzKqOaeELlDRU9kC8cC+1Ag7S+PmZ6PYrqVGChXBzFsGdsN6fVuuRLA99EheyO3zaWyymMvnqgdDsZKdFZi2eATlFeYJtlRW7EBHZiajDHJ4bvm3ExFe11l9ZpigUdLwu2S4/126mD0CkjpHqnfNVO4+NZcIHIv3hLnf8FuHmi8gSnJDf80nE7pWd8+XZPzRrB1evQvJOwKlfwzsZnXrW4ZtBFX0/9v5fwC4XnLCfGuXYjJGGndvmmPtMyK33iPb2ZGB54BAw4RcFi1ZFJMiNU6gepJbB/v3nfdeH2v+uZgzVlH1WHYJEc5j7lYZDs/wvo1DSJwHPA+VcQ2bMmoDndZI8MXpMLmVzNhCr71WilNYuaIUEdKNNcqYg3dqfebRjMIrtcYL18zmr3qUXuCVRnEiGkblg5UmGGRnqPhzBdKfm3wUsHHuZaWr8x4CYI7n3ky/ogMQeJN1J59sLm0SRY7EtT1mOuh3il4e43yfY+n2gXY7pbSpm6SZiOcfistFne5udnXf/ygKN3AZiY0q0WfxISNDbG481mIftopTNV72p7MNgUAVDMPKvwDZY7TpWujTEjUNk664cV4zLGB8mT2lqs7Qpvw2z+WCvseqi5N1WX1XTANYTFWk6uk=
